import { User } from '@/types';

export const fakeData: User[] = [
  {
    id: '1',
    firstName: 'Amadou',
    lastName: 'Mbida',
    email: 'amadou.mbida@example.com',
    state: 'Centre',
    memberships: 'Cenadi',
    profile: 'Admin',
  },
  {
    id: '2',
    firstName: 'Fatimatou',
    lastName: 'Njoya',
    email: 'fatimatou.njoya@example.com',
    state: 'Littoral',
    memberships: 'Minesup',
    profile: 'Admin',
  },
  {
    id: '3',
    firstName: 'Jean',
    lastName: 'Eboa',
    email: 'jean.eboa@example.com',
    state: 'Sud',
    memberships: 'Ipes',
    profile: 'Admin',
  },
  {
    id: '4',
    firstName: 'Marie',
    lastName: 'Ndongo',
    email: 'marie.ndongo@example.com',
    state: 'Est',
    memberships: 'Cenadi',
    profile: 'Admin',
  },
  {
    id: '5',
    firstName: 'Pierre',
    lastName: 'Essomba',
    email: 'pierre.essomba@example.com',
    state: 'Ouest',
    memberships: 'Minesup',
    profile: 'Admin',
  },
  {
    id: '6',
    firstName: 'Raissa',
    lastName: 'Mballa',
    email: 'raissa.mballa@example.com',
    state: 'Nord',
    memberships: 'Ipes',
    profile: 'Admin',
  },
  {
    id: '7',
    firstName: 'Serge',
    lastName: 'Atangana',
    email: 'serge.atangana@example.com',
    state: 'Adamaoua',
    memberships: 'Cenadi',
    profile: 'Admin',
  },
  {
    id: '8',
    firstName: 'Yvonne',
    lastName: 'Meyo',
    email: 'yvonne.meyo@example.com',
    state: 'Nord-Ouest',
    memberships: 'Minesup',
    profile: 'Admin',
  },
  {
    id: '9',
    firstName: 'Alain',
    lastName: 'Owona',
    email: 'alain.owona@example.com',
    state: 'Sud-Ouest',
    memberships: 'Ipes',
    profile: 'Admin',
  },
  {
    id: '10',
    firstName: 'Brigitte',
    lastName: 'Zogo',
    email: 'brigitte.zogo@example.com',
    state: 'Extrême-Nord',
    memberships: 'Cenadi',
    profile: 'Admin',
  },
  {
    id: '11',
    firstName: 'Charles',
    lastName: 'Etoga',
    email: 'charles.etoga@example.com',
    state: 'Centre',
    memberships: 'Minesup',
    profile: 'Admin',
  },
  {
    id: '12',
    firstName: 'Danielle',
    lastName: 'Nanga',
    email: 'danielle.nanga@example.com',
    state: 'Littoral',
    memberships: 'Ipes',
    profile: 'Admin',
  },
  {
    id: '13',
    firstName: 'Eric',
    lastName: 'Olinga',
    email: 'eric.olinga@example.com',
    state: 'Sud',
    memberships: 'Cenadi',
    profile: 'Admin',
  },
  {
    id: '14',
    firstName: 'Françoise',
    lastName: 'Eyenga',
    email: 'francoise.eyenga@example.com',
    state: 'Est',
    memberships: 'Minesup',
    profile: 'Admin',
  },
  {
    id: '15',
    firstName: 'Georges',
    lastName: 'Mbarga',
    email: 'georges.mbarga@example.com',
    state: 'Ouest',
    memberships: 'Ipes',
    profile: 'Admin',
  },
  {
    id: '16',
    firstName: 'Henriette',
    lastName: 'Ngono',
    email: 'henriette.ngono@example.com',
    state: 'Nord',
    memberships: 'Cenadi',
    profile: 'Admin',
  },
  {
    id: '17',
    firstName: 'Ibrahim',
    lastName: 'Djoumessi',
    email: 'ibrahim.djoumessi@example.com',
    state: 'Adamaoua',
    memberships: 'Minesup',
    profile: 'Admin',
  },
  {
    id: '18',
    firstName: 'Jacqueline',
    lastName: 'Foning',
    email: 'jacqueline.foning@example.com',
    state: 'Nord-Ouest',
    memberships: 'Ipes',
    profile: 'Admin',
  },
  {
    id: '19',
    firstName: 'Karim',
    lastName: 'Tchouta',
    email: 'karim.tchouta@example.com',
    state: 'Sud-Ouest',
    memberships: 'Cenadi',
    profile: 'Admin',
  },
  {
    id: '20',
    firstName: 'Lucie',
    lastName: 'Yomba',
    email: 'lucie.yomba@example.com',
    state: 'Extrême-Nord',
    memberships: 'Minesup',
    profile: 'Admin',
  },
  {
    id: '21',
    firstName: 'Marcel',
    lastName: 'Ewane',
    email: 'marcel.ewane@example.com',
    state: 'Centre',
    memberships: 'Ipes',
    profile: 'Admin',
  },
  {
    id: '22',
    firstName: 'Nadine',
    lastName: 'Mengue',
    email: 'nadine.mengue@example.com',
    state: 'Littoral',
    memberships: 'Cenadi',
    profile: 'Admin',
  },
  {
    id: '23',
    firstName: 'Olivier',
    lastName: 'Abanda',
    email: 'olivier.abanda@example.com',
    state: 'Sud',
    memberships: 'Minesup',
    profile: 'Admin',
  },
  {
    id: '24',
    firstName: 'Paulette',
    lastName: 'Obama',
    email: 'paulette.obama@example.com',
    state: 'Est',
    memberships: 'Ipes',
    profile: 'Admin',
  },
  {
    id: '25',
    firstName: 'Quentin',
    lastName: 'Nguema',
    email: 'quentin.nguema@example.com',
    state: 'Ouest',
    memberships: 'Cenadi',
    profile: 'Admin',
  },
];

//50 us states array
export const regions = [
  'Nord',
  'Centre',
  'Extrême-Nord',
  'Sud-Ouest',
  'Ouest',
  'Adamaoua',
  'Littoral',
  'Sud',
  'Est',
  'Nord-Ouest',
];

export const profiles = [
  'Admin',
  'Lecturer',
  'Syllabus Manager',
  'University Admin',
  'Ipes Manager',
  'Document Manager',
  'User Manager',
  'Level Coordinator',
  'Branch Supervisor',
  'General Viewer',
];
