import { Ues } from '@/types';

export const fakeData: Ues[] = [
  {
    id: '1',
    ue_name: 'Introduction à la littérature camerounaise',
    slug: 'intro-litt-camerounaise',
    nbr_hours: 30,
    description:
      'Exploration des œuvres littéraires clés du Cameroun, de la période coloniale à nos jours.',
    user_creator: 'Prof. Jean-Marie Essomba',
  },
  {
    id: '2',
    ue_name: "Histoire de l'Afrique centrale",
    slug: 'histoire-afrique-centrale',
    nbr_hours: 45,
    description:
      "Étude approfondie de l'histoire de l'Afrique centrale, de la préhistoire à l'époque contemporaine.",
    user_creator: 'Dr. Marie-Thérèse Atangana',
  },
  {
    id: '3',
    ue_name: "Mathématiques pour l'ingénierie",
    slug: 'maths-ingenierie',
    nbr_hours: 60,
    description:
      "Cours de mathématiques appliquées à l'ingénierie, couvrant l'algèbre linéaire, le calcul différentiel et intégral, et les équations différentielles.",
    user_creator: 'Dr. Pierre-Alain Nguema',
  },
  {
    id: '4',
    ue_name: 'Biologie cellulaire et moléculaire',
    slug: 'biologie-cell-mol',
    nbr_hours: 40,
    description:
      'Étude de la structure et des fonctions des cellules et des molécules qui les composent.',
    user_creator: 'Prof. Brigitte Owona',
  },
  {
    id: '5',
    ue_name: 'Droit constitutionnel camerounais',
    slug: 'droit-const-camerounais',
    nbr_hours: 35,
    description:
      'Analyse détaillée de la Constitution camerounaise et de son application pratique.',
    user_creator: 'Maître Amadou Mbarga',
  },
  {
    id: '6',
    ue_name: 'Géographie du Cameroun',
    slug: 'geographie-cameroun',
    nbr_hours: 25,
    description:
      'Exploration des différentes régions du Cameroun, de leur climat, de leur relief, de leur population et de leurs ressources naturelles.',
    user_creator: 'Dr. Ibrahim Foning',
  },
  {
    id: '7',
    ue_name: 'Philosophie africaine',
    slug: 'philosophie-africaine',
    nbr_hours: 30,
    description:
      "Introduction aux grandes pensées philosophiques africaines, de l'Égypte ancienne à nos jours.",
    user_creator: 'Prof. Jacqueline Meyo',
  },
  {
    id: '8',
    ue_name: 'Sociologie des organisations',
    slug: 'sociologie-organisations',
    nbr_hours: 40,
    description:
      'Étude des structures et des dynamiques sociales au sein des organisations.',
    user_creator: 'Dr. Charles Etoga',
  },
  {
    id: '9',
    ue_name: 'Langues et cultures du Cameroun',
    slug: 'langues-cultures-cameroun',
    nbr_hours: 35,
    description:
      'Aperçu de la diversité linguistique et culturelle du Cameroun.',
    user_creator: 'Prof. Danielle Eboa',
  },
  {
    id: '10',
    ue_name: 'Économie du développement',
    slug: 'economie-developpement',
    nbr_hours: 45,
    description:
      "Analyse des théories et des politiques de développement économique, avec un accent particulier sur l'Afrique.",
    user_creator: 'Dr. Eric Olinga',
  },
  {
    id: '11',
    ue_name: "Sciences de l'environnement",
    slug: 'sciences-environnement',
    nbr_hours: 30,
    description:
      "Étude des interactions entre l'homme et son environnement, et des enjeux liés à la protection de la nature.",
    user_creator: 'Prof. Françoise Eyenga',
  },
  {
    id: '12',
    ue_name: 'Informatique fondamentale',
    slug: 'informatique-fondamentale',
    nbr_hours: 50,
    description:
      "Introduction aux concepts de base de l'informatique, de la programmation aux réseaux.",
    user_creator: 'Dr. Georges Tchouta',
  },
  {
    id: '13',
    ue_name: 'Psychologie sociale',
    slug: 'psychologie-sociale',
    nbr_hours: 35,
    description: 'Étude des comportements et des interactions sociales.',
    user_creator: 'Prof. Henriette Nanga',
  },
  {
    id: '14',
    ue_name: 'Statistiques appliquées',
    slug: 'statistiques-appliquees',
    nbr_hours: 40,
    description:
      "Cours de statistiques appliquées aux sciences sociales et à l'économie.",
    user_creator: 'Dr. Karim Djoumessi',
  },
  {
    id: '15',
    ue_name: 'Anthropologie culturelle',
    slug: 'anthropologie-culturelle',
    nbr_hours: 30,
    description:
      "Étude des cultures humaines à travers le monde, avec un focus sur l'Afrique.",
    user_creator: 'Prof. Lucie Yomba',
  },
  {
    id: '16',
    ue_name: 'Relations internationales',
    slug: 'relations-internationales',
    nbr_hours: 45,
    description:
      'Analyse des relations entre les États et les organisations internationales.',
    user_creator: 'Dr. Marcel Abanda',
  },
  {
    id: '17',
    ue_name: 'Littérature française',
    slug: 'litterature-francaise',
    nbr_hours: 35,
    description:
      'Exploration des grands courants de la littérature française, du Moyen Âge à nos jours.',
    user_creator: 'Prof. Nadine Mengue',
  },
  {
    id: '18',
    ue_name: 'Chimie organique',
    slug: 'chimie-organique',
    nbr_hours: 50,
    description: 'Étude des composés du carbone et de leurs réactions.',
    user_creator: 'Dr. Olivier Nguema',
  },
  {
    id: '19',
    ue_name: 'Physique générale',
    slug: 'physique-generale',
    nbr_hours: 60,
    description:
      "Cours de physique fondamentale, couvrant la mécanique, l'électromagnétisme, la thermodynamique et l'optique.",
    user_creator: 'Prof. Paulette Obama',
  },
  {
    id: '20',
    ue_name: "Histoire de l'art africain",
    slug: 'histoire-art-africain',
    nbr_hours: 25,
    description:
      "Découverte des principales formes d'art africain, de la sculpture à la peinture en passant par l'architecture.",
    user_creator: 'Dr. Quentin Mbida',
  },
  {
    id: '21',
    ue_name: 'Communication et médias',
    slug: 'communication-medias',
    nbr_hours: 30,
    description: 'Analyse des médias et de leur rôle dans la société.',
    user_creator: 'Prof. Raissa Njoya',
  },
  {
    id: '22',
    ue_name: 'Santé publique',
    slug: 'sante-publique',
    nbr_hours: 40,
    description:
      'Étude des enjeux de santé publique au Cameroun et dans le monde.',
    user_creator: 'Dr. Serge Zogo',
  },
];

//50 us states array
export const usStates = [
  'Alabama',
  'Alaska',
  'Arizona',
  'Arkansas',
  'California',
  'Colorado',
  'Connecticut',
  'Delaware',
  'Florida',
  'Georgia',
  'Hawaii',
  'Idaho',
  'Illinois',
  'Indiana',
  'Iowa',
  'Kansas',
  'Kentucky',
  'Louisiana',
  'Maine',
  'Maryland',
  'Massachusetts',
  'Michigan',
  'Minnesota',
  'Mississippi',
  'Missouri',
  'Montana',
  'Nebraska',
  'Nevada',
  'New Hampshire',
  'New Jersey',
  'New Mexico',
  'New York',
  'North Carolina',
  'North Dakota',
  'Ohio',
  'Oklahoma',
  'Oregon',
  'Pennsylvania',
  'Rhode Island',
  'South Carolina',
  'South Dakota',
  'Tennessee',
  'Texas',
  'Utah',
  'Vermont',
  'Virginia',
  'Washington',
  'West Virginia',
  'Wisconsin',
  'Wyoming',
  'Puerto Rico',
];
